# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.1.0
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Set up Python 3.10
      uses: actions/setup-python@v4.3.0
      with:
        python-version: "3.10"
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
    - name: Test with pytest
      run: |
        python -m pytest rawsight --cache-clear --cov=rawsight | tee pytest-coverage.txt
    - name: Pytest coverage report
      uses: MishaKav/pytest-coverage-comment@v1.1.39
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        github-token: ${{ secrets.GITHUB_TOKEN }}
        default-branch: master
    - name: Update Readme with Coverage Html
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' ./README.md
    - name: Commit & Push changes to Readme
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: actions-js/push@master
      with:
        message: Update coverage on Readme [skip ci]
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        force: true
