# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.1.0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
    - name: Test with pytest
      run: |
        python -m pytest rawsight --cache-clear --cov=rawsight | tee pytest-coverage.txt
    - name: Pytest coverage report
      uses: MishaKav/pytest-coverage-comment@v1.1.32
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        token: ${{ secrets.GITHUB_TOKEN }}
